<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>$(AetherfitVersion)</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PackageProjectUrl>https://github.com/Kussie/Aetherfit</PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IconUrl>https://raw.githubusercontent.com/Kussie/Aetherfit/master/Data/icon-square.png</IconUrl>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\Data\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Visible>false</Visible>
    </Content>
    <EmbeddedResource Include="Resources\composite_tags.json">
      <LogicalName>Aetherfit.composite_tags.json</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Glamourer.Api" Version="2.8.2" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.28.0" />
    <PackageReference Include="PDFsharp" Version="6.2.4" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Penumbra.Api\Penumbra.Api.csproj" />
    <ProjectReference Include="..\Penumbra.GameData\Penumbra.GameData.csproj" />
  </ItemGroup>
</Project>
